### ISSUE TITLE
Fixer never called in 0.3.0

### ISSUE THREAD

**Issue by cominixo** [xen-42/outer-wilds-localization-utility#13]
In 0.3.0, when adding a fixer the function will never actually be called, since the fixer is trying to be called in https://github.com/xen-42/outer-wilds-localization-utility/blob/main/LocalizationUtility/CustomLanguage.cs#L68 which is called by RegisterLanguage. As there is no way to register the fixer before calling RegisterLanguage, this ends up breaking fixers.

Edit: Redundantly calling the new AddTranslation method to re-add all the translations after registering the language and the fixer fixes this, though of course this is only a workaround

**Comment by xen-42** [comment]
Whoops, should be fixed now in 0.3.1 let me know

**Comment by cominixo** [comment]
Yep that fixed it, thanks!

**Comment by xen-42** [comment]
thanks for the report!
